In [1]:
import numpy as np

In [2]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
x.shape

(3, 3)

In [4]:
x.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [5]:
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
x.sum(axis=0)

array([12, 15, 18])

In [7]:
x.sum(axis=1)

array([ 6, 15, 24])

In [8]:
# Creating a 3D Array
x = np.zeros((3,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
x = np.ones((3,3))
print(x)
x.shape

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


(3, 3)

In [10]:
a = np.array([1,2,3,4,5,6,7])
print(a)
print(a[3])
print(a[0:4])



[1 2 3 4 5 6 7]
4
[1 2 3 4]


In [11]:
# modifying an Array

a[2]=11
print(a)

[ 1  2 11  4  5  6  7]


In [12]:
a = np.array([[11,12,13],[1,1,1]])
print(a)

[[11 12 13]
 [ 1  1  1]]


In [13]:
# Accesing an element

print(a[0,0])
print(a[1,2])

11
1


In [14]:
z = np.array([[1,11,101],[2,22,222],[31,32,33]])
print(z)
z.shape

[[  1  11 101]
 [  2  22 222]
 [ 31  32  33]]


(3, 3)

In [15]:
z[1,2]

222

In [16]:
# Modifying an element
z[2,0]= 00
print(z)

[[  1  11 101]
 [  2  22 222]
 [  0  32  33]]


In [17]:
z.T


array([[  1,   2,   0],
       [ 11,  22,  32],
       [101, 222,  33]])

In [18]:
z.ndim # returns dimensions

2

In [19]:
z.dtype

dtype('int32')

In [20]:
m = np.array([[[1,2,3],[4,5,6]],[[1,1,1],[2,2,2]],[[11,12,13],[14,15,16]]])
print(m)
print(m.ndim)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 1  1  1]
  [ 2  2  2]]

 [[11 12 13]
  [14 15 16]]]
3


In [21]:
m[2][0][2]

13

In [22]:
# Print 16 from the array
m[2,1,2]

16

In [23]:
# Print 2 2 2
m[1,1]

array([2, 2, 2])

In [24]:
# Array of multi Data type

arr = np.array([[1,2,3],["a","b","c"],[-11,12.49,0]])
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[['1' '2' '3']
 ['a' 'b' 'c']
 ['-11' '12.49' '0']]
(3, 3)
2
9


In [25]:
print(arr[2,1])
print(arr[1,0])


12.49
a


In [26]:
print(arr[0][0].dtype)

<U1


In [27]:
print(arr[0,1])

2


In [28]:
# USing full

arr = np.full((4,5),1)
print(arr)
print(arr.ndim)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
2


In [29]:
# Using arange()
arr_1 =np.arange(10)
arr_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
arr_2 =np.arange(11,1111,10)
print(arr_2)
len(arr_2)

[  11   21   31   41   51   61   71   81   91  101  111  121  131  141
  151  161  171  181  191  201  211  221  231  241  251  261  271  281
  291  301  311  321  331  341  351  361  371  381  391  401  411  421
  431  441  451  461  471  481  491  501  511  521  531  541  551  561
  571  581  591  601  611  621  631  641  651  661  671  681  691  701
  711  721  731  741  751  761  771  781  791  801  811  821  831  841
  851  861  871  881  891  901  911  921  931  941  951  961  971  981
  991 1001 1011 1021 1031 1041 1051 1061 1071 1081 1091 1101]


110

# Maths Operations in Nupy

In [31]:
l1 = [1,2,3,4,5]
l2 = [6,7,8,9,0]

a1 =np.array(l1)
a2 =np.array(l2)

In [32]:
l1*5

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [33]:
a1*5

array([ 5, 10, 15, 20, 25])

Append an element

In [34]:
x = np.arange(1,10,2)
print(x)

[1 3 5 7 9]


In [35]:
x = np.append(x,[[11,12,13],[14,15,16]])
x


array([ 1,  3,  5,  7,  9, 11, 12, 13, 14, 15, 16])

In [36]:
print(x)

[ 1  3  5  7  9 11 12 13 14 15 16]


In [37]:
x = np.insert(x,3,11)
x

array([ 1,  3,  5, 11,  7,  9, 11, 12, 13, 14, 15, 16])

In [38]:
x =  np.insert(x,5,[99,98,97])
x

array([ 1,  3,  5, 11,  7, 99, 98, 97,  9, 11, 12, 13, 14, 15, 16])

copy Array

In [39]:
arr_1 = np.array([[[1,2,3,4,5],[11,22,33,44,55]],[[21,31,41,51,61],[11,22,33,44,55]]])
print(arr_1)
print(arr_1.ndim)

[[[ 1  2  3  4  5]
  [11 22 33 44 55]]

 [[21 31 41 51 61]
  [11 22 33 44 55]]]
3


In [40]:
x =np.copy(arr_1)
print(x)

[[[ 1  2  3  4  5]
  [11 22 33 44 55]]

 [[21 31 41 51 61]
  [11 22 33 44 55]]]


In [41]:
y = arr_1 + x
print(y)

[[[  2   4   6   8  10]
  [ 22  44  66  88 110]]

 [[ 42  62  82 102 122]
  [ 22  44  66  88 110]]]


In [42]:
y.shape

(2, 2, 5)

***Reshape***

In [43]:
y.reshape(2,10)
y

array([[[  2,   4,   6,   8,  10],
        [ 22,  44,  66,  88, 110]],

       [[ 42,  62,  82, 102, 122],
        [ 22,  44,  66,  88, 110]]])

In [44]:
for x in y:
    print(x)

[[  2   4   6   8  10]
 [ 22  44  66  88 110]]
[[ 42  62  82 102 122]
 [ 22  44  66  88 110]]


**Joining Array**

In [47]:
a1 = np.array([[1,2,3,4],[11,22,33,44]])
print(a1)
print(a1.ndim)
print(a1.shape)

[[ 1  2  3  4]
 [11 22 33 44]]
2
(2, 4)


In [48]:
a2 = np.array([[9,8,7,6],[21,22,23,24]])
print(a2)
print(a2.ndim)
print(a2.shape)

[[ 9  8  7  6]
 [21 22 23 24]]
2
(2, 4)


In [50]:
newArray = np.concatenate((a1,a2))
print(newArray)
print(newArray.ndim)
print(newArray.shape)

[[ 1  2  3  4]
 [11 22 33 44]
 [ 9  8  7  6]
 [21 22 23 24]]
2
(4, 4)


In [53]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2))

print(arr)
print(arr.shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)


In [54]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2),axis=1)

print(arr)
print(arr.shape)

[[1 2 5 6]
 [3 4 7 8]]
(2, 4)


*** Stack***

In [55]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [56]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


Trying all the Joining Methods one by one.

In [57]:
a = np.array([[1,2,3,4,5],[6,7,8,9,0]])
b = np.array([[11,12,13,14,15],[16,17,18,19,20]])

print(f"Array a is:\n {a}")
print(f"Array b is:\n {b}")


Array a is:
 [[1 2 3 4 5]
 [6 7 8 9 0]]
Array b is:
 [[11 12 13 14 15]
 [16 17 18 19 20]]


***concatenate()***

In [64]:
c = np.concatenate((a,b),axis =0)
print(f"Array c is:\n {c}")
print(f"Shape of c is {c.shape}")


Array c is:
 [[ 1  2  3  4  5]
 [ 6  7  8  9  0]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Shape of c is (4, 5)


In [65]:
c = np.concatenate((a,b),axis =1)
print(f"Array c is:\n {c}")
print(f"Shape of c is {c.shape}")

Array c is:
 [[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9  0 16 17 18 19 20]]
Shape of c is (2, 10)


***stack()***

In [66]:
c = np.stack((a,b),axis =0)
print(f"Array c is:\n {c}")
print(f"Shape of c is {c.shape}")

Array c is:
 [[[ 1  2  3  4  5]
  [ 6  7  8  9  0]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
Shape of c is (2, 2, 5)


In [67]:
c = np.stack((a,b),axis =1)
print(f"Array c is:\n {c}")
print(f"Shape of c is {c.shape}")

Array c is:
 [[[ 1  2  3  4  5]
  [11 12 13 14 15]]

 [[ 6  7  8  9  0]
  [16 17 18 19 20]]]
Shape of c is (2, 2, 5)


***hstack()***

In [68]:
c = np.hstack((a,b))
print(f"Array c is:\n {c}")
print(f"Shape of c is {c.shape}")

Array c is:
 [[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9  0 16 17 18 19 20]]
Shape of c is (2, 10)


***vstack()***

In [70]:
c = np.vstack((a,b))
print(f"Array c is:\n {c}")
print(f"Shape of c is {c.shape}")

Array c is:
 [[ 1  2  3  4  5]
 [ 6  7  8  9  0]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Shape of c is (4, 5)


***dstack()***

In [73]:
c = np.vstack((a,b))
print(f"Array c is:\n {c}")
print(f"Shape of c is {c.shape}")

Array c is:
 [[ 1  2  3  4  5]
 [ 6  7  8  9  0]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Shape of c is (4, 5)


***array_split()***

In [83]:
a = np.array([1,2,3,4,5,6,7,8])
print(a)
print(a.shape)

[1 2 3 4 5 6 7 8]
(8,)


In [84]:
m =  np.array_split(a,2)
print(m)

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]


In [85]:
m =  np.array_split(a,3)
print(m)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]


In [86]:
m =  np.array_split(a,4)
print(m)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


In [87]:
m =  np.array_split(a,6)
print(m)

[array([1, 2]), array([3, 4]), array([5]), array([6]), array([7]), array([8])]


***Using array_split() in 2D array***

In [88]:
x = np.array([[1,2,3,4,5],[11,22,33,44,55]])
print(x)
print(x.shape)

[[ 1  2  3  4  5]
 [11 22 33 44 55]]
(2, 5)


In [90]:
y = np.array_split(x,2)
print(y)

[array([[1, 2, 3, 4, 5]]), array([[11, 22, 33, 44, 55]])]


In [93]:
y = np.array_split(x,3)
print(y)


[array([[1, 2, 3, 4, 5]]), array([[11, 22, 33, 44, 55]]), array([], shape=(0, 5), dtype=int32)]


In [94]:
y = np.array_split(x,4)
print(y)


[array([[1, 2, 3, 4, 5]]), array([[11, 22, 33, 44, 55]]), array([], shape=(0, 5), dtype=int32), array([], shape=(0, 5), dtype=int32)]


*** Searching using where() ***

In [95]:
x = np.array([[1,2,3,4,5],[11,22,33,44,55]])
print(x)
print(x.shape)

[[ 1  2  3  4  5]
 [11 22 33 44 55]]
(2, 5)


In [97]:
y = np.where(x==33)
print(y)

(array([1], dtype=int64), array([2], dtype=int64))


In [98]:
y = np.where(x==5)
print(y)

(array([0], dtype=int64), array([4], dtype=int64))


Searching even elements

In [99]:
y = np.where(x%2==0)
print(y)

(array([0, 0, 1, 1], dtype=int64), array([1, 3, 1, 3], dtype=int64))


Searching even elements

In [100]:
y = np.where(x%2!=0)
print(y)

(array([0, 0, 0, 1, 1, 1], dtype=int64), array([0, 2, 4, 0, 2, 4], dtype=int64))


***Sort()***

In [103]:
x = np.array([[4,1,3,5,2],[44,11,22,55,33]])
print(x)

[[ 4  1  3  5  2]
 [44 11 22 55 33]]


In [104]:
y = np.sort(x)
print(y)

[[ 1  2  3  4  5]
 [11 22 33 44 55]]
