# Difference between List and Numpy


NumPy gives you an enormous range of fast and efficient ways of creating arrays and manipulating numerical data inside them. While a Python list can contain different data types within a single list, all of the elements in a NumPy array should be homogeneous.

# Why use NumPy?

 NumPy uses much less memory to store data and it provides a mechanism of specifying the data types.
 An array consumes less memory and is convenient to use.

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)
print(type(a))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [3]:
a.shape

(6,)

In [4]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12],[13,14,15,16]])
print(b)
b.shape

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


(4, 4)

In [5]:
#creating a 2D array.
c = np.array([[11,12,13],[14,15,16]])
print(c)
c.shape

[[11 12 13]
 [14 15 16]]


(2, 3)

Indexing in NumPy starts at 0.

In [6]:
#Accessing an element(s) from array


print(c[0][1])
print(c[1][2])

12
16


In [7]:
#Create zeros and Ones using numpy.

a = np.zeros(3)
print(a)
a.shape

[0. 0. 0.]


(3,)

In [8]:
a = np.ones(5)
print(a)
a.shape

[1. 1. 1. 1. 1.]


(5,)

In [9]:
a = np.empty(2)
print(a)
a.shape

[-1.84013723e-253  5.05277950e-077]


(2,)

In [10]:
#create an array with a range of elements:
a =np.arange(10)
print(a)


[0 1 2 3 4 5 6 7 8 9]


In [11]:
#Create an even range of array where: firstNumber,LastNumber,stepsize

a = np.arange(2,19,2)
print(a)
len(a)

[ 2  4  6  8 10 12 14 16 18]


9

In [12]:
#Create an odd range of array where: firstNumber,LastNumber,stepsize
a = np.arange(1,16,2)
print(a)
len(a)

[ 1  3  5  7  9 11 13 15]


8